version: '2'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - /work/docker/draguo/src/:/usr/share/nginx/html

  php_fpm:
    build: ./php
    volumes:
        - /work/docker/draguo/src/:/usr/share/nginx/html